DEL abcexport.d
DEL abcexport.exe
DEL abcfile.d
DEL abcreplace.d
DEL abcreplace.exe
DEL asasm.hrc
DEL asprogram.d
DEL assembler.d
DEL autodata.d
DEL build_rabcdasm.d
DEL CHANGELOG.md
DEL common.d
DEL COPYING
DEL disassembler.d
DEL liblzma.dll
DEL liblzma.lib
DEL lzma.d
DEL main.o
DEL Makefile.win
DEL murmurhash2a.d
DEL rabcasm.d
DEL rabcasm.exe
DEL rabcdasm.d
DEL rabcdasm.exe
DEL rabcdasm_easy.exe
DEL README.md
DEL swf7zcompress.d
DEL swf7zcompress.exe
DEL swfbinexport.d
DEL swfbinexport.exe
DEL swfbinreplace.d
DEL swfbinreplace.exe
DEL swfdecompress.d
DEL swfdecompress.exe
DEL swffile.d
DEL swflzmacompress.d
DEL swflzmacompress.exe
DEL zlibx.d
DEL deimos\lzma.d
DEL deimos\lzma_\base.d
DEL deimos\lzma_\bcj.d
DEL deimos\lzma_\block.d
DEL deimos\lzma_\check.d
DEL deimos\lzma_\container.d
DEL deimos\lzma_\delta.d
DEL deimos\lzma_\filter.d
DEL deimos\lzma_\hardware.d
DEL deimos\lzma_\index.d
DEL deimos\lzma_\index_hash.d
DEL deimos\lzma_\lzma.d
DEL deimos\lzma_\stream_flags.d
DEL deimos\lzma_\version_.d
DEL deimos\lzma_\vli.d
DELTREE deimos
RD deimos\lzma_
RD deimos\
DEL rabcdasm_easy.Form1.resources
DEL rabcdasm_easy.Properties.Resources.resources
DEL Form1.resources
DEL Properties.Resources.resources
DEL rabcdasm_easy.rin.bat
DEL 01.bat
DEL 02.bat
DEL rabcdasm_easy.rabcdasm_easy.exe
DEL rabcdasm_easy.AboutBox1.resources

del del.bat