rename rabcdasm_easy.abcexport.d abcexport.d
rename rabcdasm_easy.abcexport.exe abcexport.exe
rename rabcdasm_easy.abcfile.d abcfile.d
rename rabcdasm_easy.abcreplace.d abcreplace.d
rename rabcdasm_easy.abcreplace.exe abcreplace.exe
rename rabcdasm_easy.asasm.hrc asasm.hrc
rename rabcdasm_easy.asprogram.d asprogram.d
rename rabcdasm_easy.assembler.d assembler.d
rename rabcdasm_easy.autodata.d autodata.d
rename rabcdasm_easy.build_rabcdasm.d build_rabcdasm.d 
rename rabcdasm_easy.CHANGELOG.md CHANGELOG.md
rename rabcdasm_easy.common.d common.d
rename rabcdasm_easy.COPYING COPYING
rename rabcdasm_easy.disassembler.d disassembler.d
rename rabcdasm_easy.Form1.resources Form1.resources
rename rabcdasm_easy.liblzma.dll liblzma.dll
rename rabcdasm_easy.liblzma.lib liblzma.lib
rename rabcdasm_easy.lzma.d lzma.d
rename rabcdasm_easy.main.o main.o
rename rabcdasm_easy.Makefile.win Makefile.win
rename rabcdasm_easy.murmurhash2a.d murmurhash2a.d
rename rabcdasm_easy.Properties.Resources.resources Properties.Resources.resources
rename rabcdasm_easy.rabcasm.d rabcasm.d
rename rabcdasm_easy.rabcasm.exe rabcasm.exe
rename rabcdasm_easy.rabcdasm.d rabcdasm.d
rename rabcdasm_easy.rabcdasm.exe rabcdasm.exe
rename rabcdasm_easy.rabcdasm_easy.exe rabcdasm_easy.exe
rename rabcdasm_easy.README.md README.md
rename rabcdasm_easy.swf7zcompress.d swf7zcompress.d
rename rabcdasm_easy.swf7zcompress.exe swf7zcompress.exe
rename rabcdasm_easy.swfbinexport.d swfbinexport.d
rename rabcdasm_easy.swfbinexport.exe swfbinexport.exe
rename rabcdasm_easy.swfbinreplace.d swfbinreplace.d
rename rabcdasm_easy.swfbinreplace.exe swfbinreplace.exe
rename rabcdasm_easy.swfdecompress.d swfdecompress.d
rename rabcdasm_easy.swfdecompress.exe swfdecompress.exe
rename rabcdasm_easy.swffile.d swffile.d
rename rabcdasm_easy.swflzmacompress.d swflzmacompress.d
rename rabcdasm_easy.swflzmacompress.exe swflzmacompress.exe
rename rabcdasm_easy.zlibx.d zlibx.d
rename rabcdasm_easy.del.bat del.bat
MD deimos
MD deimos\lzma_
MOVE rabcdasm_easy.lzma.d2 deimos\lzma.d
MOVE rabcdasm_easy.base.d deimos\lzma_\base.d
MOVE rabcdasm_easy.bcj.d deimos\lzma_\bcj.d
MOVE rabcdasm_easy.block.d deimos\lzma_\block.d
MOVE rabcdasm_easy.check.d deimos\lzma_\check.d
MOVE rabcdasm_easy.container.d deimos\lzma_\container.d
MOVE rabcdasm_easy.delta.d deimos\lzma_\delta.d
MOVE rabcdasm_easy.filter.d deimos\lzma_\filter.d
MOVE rabcdasm_easy.hardware.d deimos\lzma_\hardware.d
MOVE rabcdasm_easy.index.d deimos\lzma_\index.d
MOVE rabcdasm_easy.index_hash.d deimos\lzma_\index_hash.d
MOVE rabcdasm_easy.lzma.d3 deimos\lzma_\lzma.d
MOVE rabcdasm_easy.stream_flags.d deimos\lzma_\stream_flags.d
MOVE rabcdasm_easy.version_.d deimos\lzma_\version_.d
MOVE rabcdasm_easy.vli.d deimos\lzma_\vli.d
